# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160512_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(default='Opinion', max_length=25),
        ),
    ]
